version: '3'
services:
  api:
    container_name: api_container
    image: node:14
    working_dir: /usr/src/clean-typescript-api
    restart: always
    command: bash -c "yarn install --only=prod && yarn start"
    environment:
      - PORT=5050
      - MONGO_URL=mongodb://mongo:27017/clean-typescript-api
      - JWT_SECRET_KEY="secret_key
    volumes:
      - ./dist/:/usr/src/clean-typescript-api/dist/
      - ./package.json:/usr/src/clean-typescript-api/package.json
    ports:
      - '5050:5050'
      - '9222:9222'
    networks:
      - clean-typescript-api

  mongo:
    container_name: mongo_container
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db
    ports:
      - '27017:27017'
    networks:
      - clean-typescript-api

networks:
  clean-typescript-api:

volumes:
  mongodb:
