version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  api:
    container_name: api-container
    build: .
    image: clean-typescript-api
    restart: always
    command: yarn start
    volumes:
      - ./dist:/usr/src/clean-typescript-api/dist
      - ./package.json:/usr/src/clean-typescript-api/package.json
    ports:
      - '5050:5050'
      - '9222:9222'
    links:
      - mongo
